### ISSUE TITLE
Nginx configuration

### ISSUE THREAD

**Issue by QuicksilverMachine** [calpaterson/python-web-perf#2]
Would you mind sharing your top-level nginx configuration used for this test? I consistently ran into problems with too many open file descriptors on the os level and couldn't get throughputs this large.

**Comment by calpaterson** [comment]
Hi!

The "per-site" config is here: https://github.com/calpaterson/python-web-perf/blob/master/nginx.conf

For the rest of the config, I used the default ubuntu config from 20.04

**Comment by QuicksilverMachine** [comment]
Thanks, that helps. I'll look into my configuration a bit more.
